#!/bin/sh

### BEGIN INIT INFO
# Provides:          phidgetwebservice
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Should-Start:      avahi
# Should-Stop:       avahi
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Phidget Loggingservice
# Description:       Phidget Loggingservice for controlling Phidgets over the network.
### END INIT INFO

DESC="Phidget Loggingservice"
NAME=phidgetlogging
BIN=phidgetlogging21
DAEMON=/root/DataLoggerProject/SBCLogger/$BIN
#DAEMON=/usr/bin/$BIN
PIDFILE=/var/run/$NAME.pid
CFG=/etc/default/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# load config
pws_enabled="true"
#pws_port="5001"
#pws_serverid=""
#pws_password=""
[ -f $CFG ] && . $CFG

start() {
	OPTIONS=""
	#[ -z "$pws_port" ] || OPTIONS="-p $pws_port "
	#[ -z "$pws_password" ] || OPTIONS="$OPTIONS-P $pws_password "

	#if [ -z "$pws_serverid" ]; then
		#OPTIONS="$OPTIONS -n $( hostname )"
	#else
		#OPTIONS="$OPTIONS -n $pws_serverid"
	#fi
	
	echo -n "Starting $DESC: "
	echo "start-stop-daemon -S -b -q -p $PIDFILE -m -x $DAEMON"
	#start-stop-daemon -S -b -q -p $PIDFILE -m -x $DAEMON && echo "OK" || echo "ALREADY RUNNING"
	start-stop-daemon --start --oknodo --pidfile $PIDFILE --startas $DAEMON start
}

stop() {
	echo -n "Stopping $DESC: "
	echo "start-stop-daemon -K -q -p $PIDFILE -x $DAEMON"
	#start-stop-daemon -K -q -p $PIDFILE -x $DAEMON && echo "OK" || echo "NOT RUNNING"
	start-stop-daemon --stop --oknodo --pidfile $PIDFILE
}

case "$1" in
  forcestart)
	start
	;;
  start)
	if [ "$pws_enabled" = "true" ]; then
		start
	else
		echo "Not starting Phidget Loggingservice."
		exit 0
	fi
	;;
  stop)
	stop
	;;
  restart|force-reload)
	stop
	sleep 1
	if [ "$pws_enabled" = "true" ]; then
		start
	else
		echo "Not starting Phidget Loggingservice."
		exit 0
	fi
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
esac

exit 0
